name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm ci

      # The REST DataSource unit tests require the app_config.json file
      - name: Add config file
        run: |
          mkdir config
          cd config
          echo '{"api_key": ""}' > app_config.json

      - run: npm test
