name: pull_request

on: [pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci

      # The REST DataSource unit tests require the app_config.json file
      - name: Add config file
        run: |
          mkdir config
          cd config
          echo '{"api_key": ""}' > app_config.json

      - run: npm test
